# Generated by Django 4.1.3 on 2022-11-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.picture",
            ),
        ),
    ]
