# Generated by Django 4.1.3 on 2022-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
